version: "3.9"

name: nchcsystem

networks:
  nchc:
    external: false

services:
  nchc_searxng:
    container_name: nchc_searxng  
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
      - 32768:32768
    restart: unless-stopped
    networks:
      - nchc

  nchc_perplexica-backend:
    container_name: nchc_perplexica-backend    
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://nchc_searxng:8080
    ports:
      - 3001:3001
    volumes:
      - ./backend-dbstore:/home/perplexica/data
      #- ./config_new.toml:/home/perplexica/config.toml
    restart: unless-stopped
    networks:
      - nchc
    extra_hosts:
      - host.docker.internal:host-gateway         
    depends_on:
      - nchc_searxng
      
  nchc_perplexica-frontend:
    container_name: nchc_perplexica-frontend      
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://api_perplexica.biobank.org.tw/api
        - NEXT_PUBLIC_WS_URL=wss://api_perplexica.biobank.org.tw
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - nchc
    extra_hosts:
      - host.docker.internal:host-gateway       
    depends_on:
      - nchc_perplexica-backend    

  nchc_php:
    container_name: nchc_php
    image: php:8.3-fpm
    pull_policy: always    
    ports:
      - 9000:9000
    volumes:
      - ./website:/var/www/html      
    restart: always
    networks:
      - nchc     
      
  nchc_nginx:
    container_name: nchc_nginx
    image: nginx
    ports:
      -  80:80
      -  443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
      - ./website:/var/www/html  
      - ./nginx/biobank_ssl:/ssl          
    restart: always
    networks:
        - nchc       
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - nchc_perplexica-frontend  