version: "3.9"

name: nchcsystem

networks:
  nchc:
    external: false

services:
  nchc_redis:
    container_name: nchc_redis
    image: docker.io/valkey/valkey:7-alpine
    volumes:
      - ./valkey-data:/data
    restart: unless-stopped
    networks:
      - nchc      
    #cap_drop:
    #  - ALL
    #cap_add:
    #  - SETGID
    #  - SETUID
    #  - DAC_OVERRIDE
    #logging:
    #  driver: "json-file"
    #  options:
    #    max-size: "1m"
    #    max-file: "1"
    command: valkey-server --save 30 1 --loglevel warning
        
  nchc_searxng:
    container_name: nchc_searxng  
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
      - ./engines:/usr/local/searxng/searx/engines
    ports:
      - 4000:8080
      - 32768:32768
    restart: unless-stopped
    networks:
      - nchc
    #environment:
    #  - SEARXNG_BASE_URL=http://${SEARXNG_HOSTNAME:-localhost}/      
    #cap_drop:
    #  - ALL
    #cap_add:
    #  - CHOWN
    #  - SETGID
    #  - SETUID
    #logging:
    #  driver: "json-file"
    #  options:
    #    max-size: "1m"
    #    max-file: "1"      

  nchc_perplexica-backend:
    container_name: nchc_perplexica-backend    
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://nchc_searxng:8080
    ports:
      - 3001:3001
    volumes:
      - ./backend-dbstore:/home/perplexica/data
    restart: unless-stopped
    networks:
      - nchc
    extra_hosts:
      - host.docker.internal:host-gateway         
    depends_on:
      - nchc_searxng
      
  nchc_perplexica-frontend:
    container_name: nchc_perplexica-frontend      
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://api_perplexica.biobank.org.tw/api
        - NEXT_PUBLIC_WS_URL=wss://api_perplexica.biobank.org.tw
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - nchc
    extra_hosts:
      - host.docker.internal:host-gateway       
    depends_on:
      - nchc_perplexica-backend    

  nchc_translation-agent-nchc:
    container_name: nchc_translation-agent-nchc       
    image: c00cjz00/translation-agent-nchc
    volumes:
      - ./translation-agent-nchc:/translation-agent-nchc
    ports:
      - 7860:7860
    restart: unless-stopped
    networks:
      - nchc
    command: bash -c "cd /translation-agent-nchc; poetry run python app/app_nvidia.py"      

  nchc_php:
    container_name: nchc_php
    image: php:8.3-fpm
    pull_policy: always    
    ports:
      - 9000:9000
    volumes:
      - ./website:/var/www/html      
    restart: always
    networks:
      - nchc     
      
  nchc_nginx:
    container_name: nchc_nginx
    image: nginx
    ports:
      -  80:80
      -  443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
      - ./website:/var/www/html  
      - ./nginx/biobank_ssl:/ssl          
      - ./nginx_htpasswd:/nginx_htpasswd          
    restart: always
    networks:
        - nchc       
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - nchc_perplexica-frontend  